### ISSUE TITLE
Update data after async call

### ISSUE THREAD

**Issue by Hugo-Contreras** [willsoto/angular2-chartist#100]
Hi,

I'm trying to get data from an API for my chart, until that everything is ok I got my `Promise Object`.

The question is, how I can refresh the date or update them ? I can't call the `update` method on my `Promise Object` ? If I try to recall my API the `Promise Object` become empty...

```
chartData: Promise<Chartist.IChartistData>;
  type = 'Line';
  options = {
   axisX: {
      labelInterpolationFnc: function(value: number, index: number): number {
        return index % 10 === 0 ? value : null;
      }
    }
  };

  constructor(private dataService: DataService) { }

  ngOnInit() {
    this.chartData = this.dataService.getChartData().toPromise();
  }
```

**Comment by willsoto** [comment]
Are you asking how to make the chart update when it gets new data? Or are you asking something else entirely?

**Comment by Hugo-Contreras** [comment]
Yes I'm asking how to make the chart update when it gets new data. But in the particular case where you started by getting the data asynchronously from an API.

**Comment by Hugo-Contreras** [comment]
The object is a Promise and when I update it I've got an empty one and the Chart doesn't work anymore... The code I'm using is there :
https://github.com/Hugo-Contreras/angularPOC/blob/master/src/app/rates/rates.component.ts

In the reloadChart function.

**Comment by willsoto** [comment]
Right away I can see that you aren't resolving the promise [here](https://github.com/Hugo-Contreras/angularPOC/blob/master/src/app/rates/rates.component.ts#L46). You need to call `.then` and then set `this.chartData = <promise-result>`

**Comment by Hugo-Contreras** [comment]
Maybe but it works fine [the line below](https://github.com/Hugo-Contreras/angularPOC/blob/master/src/app/rates/rates.component.ts#L42)

**Comment by willsoto** [comment]
My code will technically unwrap the promise for you, so that explains why that works. If that is case it must be something going on in your code I can't see.

**Comment by Hugo-Contreras** [comment]
Ok I hoped it was a common usage, I will keep looking for figure it out. Thank's
