### ISSUE TITLE
refresh on property changes

### ISSUE THREAD

**Issue by miton18** [willsoto/angular2-chartist#95]
I would like to use this plugin: 
https://github.com/activey/chartist-plugin-line-chart-labels

In my component I have : 
```
this.options = {
      showLine: true,
      showArea: true,
      showPoint: false,
      fullWidth: true,
      plugins: [
        Chartist.plugins.lineChartLabels({
          labels: this.classNames
        })
      ]
    };
```
It is set in the component constructor. How can I tell x-chartist to update his chart when I change "this.classNames"

**Comment by willsoto** [comment]
Without knowing too many details, I would maybe have a function that sets `this.options` when `this.classNames` changes.

If you wanna post a jsfiddle or something, I can try and help more.
